# Site
name: "Michael Wright"
title: "Michael Wright"
description: "A place for me to share my thoughts and reviews."
logo: 'assets/images/logo.svg'
favicon: 'assets/images/favicon.png'
baseurl: ''
google_analytics: 'UA-173391829-1'
disqus: ''
mailchimp-list: false
include: ["_pages"]
permalink: /:title/
future: false
search: false

# Authors
authors:
  michael:
    name: Michael Wright
    display_name: Michael
    avatar: assets/images/authors/michael.jpeg
    email: spam@wserver.co.uk 
    web: https://instagram.com/michael.w.90
    twitter: https://twitter.com/michaelw90
    twitter_handle: "@michaelw90"
    description: "This is my description test"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

sass:
  style: compressed

twitter:
  username: michaelw90
  card: summary

lang: en_GB
  
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
