# Site
name: "Michael Wright"
title: "Mediumish"
description: "A head of development working in Manchester, sharing his thoughts and reviews of day-to-day things in life."
logo: 'assets/images/logo.svg'
favicon: 'assets/images/favicon.png'
baseurl: ''
google_analytics: false
disqus: ''
mailchimp-list: false
include: ["_pages"]
permalink: /:title/
future: false

# Authors
authors:
  michael:
    name: Michael Wright
    display_name: Michael
    gravatar: 5b31c071fe85f983da70d571ce8a0cee
    email: spam@wserver.co.uk 
    web: https://instagram.com/michael.w.90
    twitter: https://twitter.com/michaelw90
    description: "This is my description test"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
